config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get '/home/about' => "homes#about"
  devise_for :users
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%' + content)
    else
      Book.where('title LIKE ?', '%' + content + '%')
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
	  user_path(current_user.id)
	end

	def after_sign_out_path_for(resource)
	  root_path
	end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.user_id = current_user.id
    unless @book_comment.save
      render 'error'
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.new
    @bookf = Book.find(params[:id])
    @user = User.find(@bookf.user[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])

    user = User.find(@book.user[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])

    user = User.find(@book.user[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to request.referer
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    if @model == 'user'
      @records = User.search_for(@content, @method)
    else
      @records = Book.search_for(@content, @method)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])

    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])

    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end

    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_index.html.erb
      <table class="book_comments">
        <tbody>
          <% book.book_comments.each do |book_comment| %>
          <tr>
            <td><%= link_to user_path(book_comment.user) do %>
                  <%= image_tag book_comment.user.get_profile_image(100,100) %><br>
                  <%= book_comment.user.name %>
                <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <td><% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
                <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/error.js.erb
$("#comments_error").html("<%= j(render 'layouts/errors', obj: @book_comment) %>");

app/views/books/_index.html.erb
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% books.each do |book| %>
          <tr id="book_<%= book.id %>">
            <td><%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %></td>
            <td><%= link_to book_path(book.id) do %>
                <%= book.title %>
                <% end %></td>
            <td><%= book.body %></td>
            <td class="comments-count">コメント数: <%= book.book_comments.count %></td>
            <td class="favorite-btn"><%= render 'favorites/btn', book: book %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/books/_userinfo.html.erb
 <% if newbook.errors.any? %>
  <h3><%= newbook.errors.count %>errors prohibited this obj from being saved:</h3>
  <ul>
    <% newbook.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <h2>User info</h2>

      <%= image_tag user.get_profile_image(100,100) %>

      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
	        </tr>
	        <tr>
	          <th>follows</th>
	          <th><%= link_to user.followings.count, user_followings_path(user) %></th>
	        </tr>
	        <tr>
	          <th>followers</th>
	          <th><%= link_to user.followers.count, user_followers_path(user) %></th>
	        </tr>
	      </tbody>
	     </table>
	     <div class="row">
	       <% if current_user != user %>
	         <td><%= render 'relationships/btn', user: user %></td>
	       <% else %>
	         <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
	           <i class="fas fa-user-cog"></i>
	         <% end %>
	       <% end %>
	     </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model: newbook do |f| %>

      <div class="form-group">
      <label>Title</label><br>
      <%= f.text_field :title %>
      </div>

      <div class="form-group">
      <label>Opinion</label><br>
      <%= f.text_area :body %>
      </div>

      <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
      </div>

      <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row flex-column">
	 	<div class="mx-auto col-6">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>

      <%= form_with model: @book do |f| %>

      <div class="form-group">
      <label>Title</label><br>
      <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
      <label>Opinion</label><br>
      <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.submit 'Update Book', class:"btn btn-success" %>
      </div>

      <% end %>

      <%= link_to "Show", book_path(@book.id) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>

    <%= render 'userinfo', user: @user, newbook: @book %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <%= render 'index', books: @books %>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>

    <%= render 'userinfo', user: @user, newbook: @book %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table class="table">
        <tbody>
          <tr id="book_<%= @bookf.id %>">
            <td><%= link_to user_path(@bookf.user.id) do %>
                 <%= image_tag @bookf.user.get_profile_image(100,100) %>
                 <br>
                 <%= @bookf.user.name %></td>
                <% end %>
            <td><%= link_to book_path(@bookf) do %>
                <%= @bookf.title %>
                <% end %></td>
            <td><%= @bookf.body %></td>
            <td class="comments-count">コメント数: <%= @bookf.book_comments.count %></td>
            <td class="favorite-btn"><%= render 'favorites/btn', book: @bookf %></td>

            <% if @bookf.user == current_user %>
            <td><%= link_to edit_book_path(@bookf.id), class: "btn btn-success" do %>
                  Edit
                  <% end %></td>
            <td><%= link_to book_path(@bookf.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" do %>
                  Destroy
                  <% end %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <%= render 'book_comments/index', book: @bookf %>

      <div id="comments_error">
        <%= render 'layouts/errors', obj: @book_comment %>
      </div>

      <%= form_with(model:[@bookf, @book_comment], local: false) do |f| %>
        <%= f.text_area :comment, row:'5', placeholder: "コメントここに", class: "w-100 mt-4" %>
        <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-2 pull-right btn-info" %>
      <% end %>

    </div>

  </div>
</div>

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/btn', book: @book) %>");

app/views/homes/about.html.erb
	<div class="container">
	  <div class="row">
	  	<div class="mx-auto col-8">
	      <h1 class="text-dark p-0 mx-0 text-center">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
	    </div>
	  </div>
	</div>

app/views/homes/top.html.erb
	<div class="container animate__animated animate__bounce">
	  <div class="row flex-column">
	  	<div class="mx-auto col-8">
	      <h1 class="text-dark p-0 mx-0">welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
	      <p>In <i class="fas fa-book"></i><b>Bookers</b>,</p>
	      <p>you can share and exchange your opinions , inpressions , and emotions</p>
	      <p>about various books!</p>
	    </div>
	    <div class="row col-6 mx-auto">
	      <%= link_to "Log in", new_user_session_path, class:"btn btn-sm btn-block btn-info" %>
	      <%= link_to "Sign up", new_user_registration_path, class:"btn btn-sm btn-block btn-success mt-3" %>
	    </div>
	  </div>
	</div>

<p>下にスクロールをすると動きます</p>
<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓<br>↓

<div class="flex">
<div class="fadeInUpTrigger box">すぐ現れるボックス</div>

<%= javascript_include_tag "test" %>

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render 'users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render 'users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
  <%= f.text_field :content %>
  <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
  <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
  <%= f.submit '検索' %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'user' %>
  <h3>Users search for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% elsif @model == 'book' %>
  <h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_index.html.erb
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(80,80) %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td><%= render 'relationships/btn', user: user %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row flex-column">
	 	<div class="mx-auto col-6">
      <h1>User info</h1>
      
      <% if @user.errors.any? %>
      <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>

      <%= form_with model: @user do |f| %>

      <div class="form-group">
      <label>Name</label><br>
      <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
      <label>Image</label><br>
      <%= f.file_field :image, accept: "image/*", name: "user[profile_image]" %>
      </div>

      <div class="form-group">
      <label>Introduction</label><br>
      <%= f.text_area :introduction, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.submit 'Update User', class:"btn btn-secondary" %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>

    <%= render 'books/userinfo', user: @user, newbook: @book %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

      <%= render 'index', users: @users %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>

    <%= render 'books/userinfo', user: @user, newbook: @book %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="2"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(@user) do %>
                 <%= image_tag @user.get_profile_image(100,100) %></td>
                <% end %>
            <td><%= link_to book_path(book.id) do %>
                <%= book.title %></td>
                <% end %>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>